### ISSUE TITLE
Keyboard app has no settings menu in "Languages & input"

### ISSUE THREAD

**Issue by slashdevslashurandom** [timeopochin/tokiponakeyboard#10]
So far, the only way to change some of the settings of the toki pona keyboard is to use the app icon in your launcher. Normally, keyboard applications also allow you to change their settings in Android's input settings.

On my phone (Nokia 5, Android 9), these settings are available in (Settings -> System -> Languages & input -> Virtual keyboard), where each of the enabled keyboards has a menu item that usually connects to the keyboard's settings menu. The toki pona keyboard's settings menu doesn't do that -- clicking on its menu item does nothing.

**Comment by timeopochin** [comment]
Thank you, this would be a great feature to add, I'll make sure it is implemented for the next update

**Comment by timeopochin** [comment]
This has now been implemented in the source code and will be part of the next update :)
