### ISSUE TITLE
Fonts aren't loading in

### ISSUE THREAD

**Issue by JosephEPeterson** [timeopochin/tokiponakeyboard#2]
When using the keyboard, the sitelen pona glyphs don't load in. There is only the usual sitelen latin text. I am on a One Plus 7 Pro. I am attaching a pic of the issue 
![Screenshot_20200604-091304](https://user-images.githubusercontent.com/49570602/83767765-a3d6bb80-a643-11ea-9939-be3f1fc74bbb.jpg)

**Comment by timeopochin** [comment]
Okay, I will try to reproduce it, though if you observe the [ key, you can see that the font is active. But for some reason the text is CAPITALISED which is causing them to not be rendered by the linja pona font.

My first guess would be that there exists some setting that makes the keyboard display CAPITAL letters.

**Comment by Jab1399** [comment]
I have the same exact problem I'm on a xiaomi MI 9T running Android version 10.

**Comment by timeopochin** [comment]
I believe I have fixed it 7fcfaeb2daa3109896913ad43409e3774cc26157
It will be in the next update

**Comment by timeopochin** [comment]
Confirmed fixed in v1.0.0-alpha.3
