### ISSUE TITLE
No keyboard switching button

### ISSUE THREAD

**Issue by Jab1399** [timeopochin/tokiponakeyboard#3]
Hello! One issue I'm having is being able to switch back and forth from the toki pona keyboard to my normal Gboard. There is not a button for me to do that. Photo attached. (Also in the photo you can see that the symbols don't show up, only the Latin characters but I mentioned this already the other issue section about that)
![Screenshot_2020-06-04-13-37-42-195_com google android keep](https://user-images.githubusercontent.com/66435894/83792125-9c75d900-a668-11ea-9252-c93009daa627.jpg)

**Comment by timeopochin** [comment]
You can simply long press the send key, more info [here](https://github.com/timeopochin/tokiponakeyboard#special-behavior)
