### ISSUE TITLE
When sitelen Emoji mode is disabled, keyboard interacts poorly with emoji

### ISSUE THREAD

**Issue by slashdevslashurandom** [timeopochin/tokiponakeyboard#9]
In the regular mode, the keyboard always tries move the cursor between words. It doesn't do this in sitelen Emoji mode, because every "word" is one character long.

But when switching _between_ modes, this can cause some unexpected behaviors. If i've switched out of sitelen Emoji mode, then the keyboard treats all emoji as one single long word. The "backspace" button deletes the entire sequence of emoji, and the cursor can no longer be moved inside the sequence.

**Comment by timeopochin** [comment]
This is definitively behaviour that I will change. Thank you for the feedback!

**Comment by timeopochin** [comment]
This has been fixed in the source code and will be in the next update.
